---
- hosts: all
  become: true
  tasks:
    - name: check if files have already been copied
      stat: 
        path: "{{ drupal_core_path }}/sites/ldl.library.local"
      register: drupal_sites

    - name: mv sites/* to match /etc/hosts
      command: "mv {{ drupal_core_path }}/sites/{{ item }} {{ drupal_core_path }}/sites/{{ item }}.library.local"
      when: not drupal_sites.stat.exists
      with_items: "{{ institutions }}"